AGENT=agent_2
QOS_MAX_JOBS=16
FULL_DAY=24
LARGE_GPU_SLOW_RATE=35
E3_HOME=ch231037@e3-login.tch.harvard.edu:/home/ch231037/
PREVIOUS_INITIAL=405
PREVIOUS_JOB_COUNT=6
PREVIOUS_HOURS_PER_JOB=72
PREVIOUS_REMAINDER_FN=remainder.tsv
PREVIOUS_REMAINDER_PATH=/home/etg/r/Eli/CRICO_106k/"${AGENT}"/"${PREVIOUS_INITIAL}"_"${PREVIOUS_JOB_COUNT}"_"${PREVIOUS_HOURS_PER_JOB}"_"${PREVIOUS_REMAINDER_FN}"
CURRENT_INITIAL=$(expr ${PREVIOUS_INITIAL} + ${PREVIOUS_JOB_COUNT})
CURRENT_JOB_COUNT=16
CURRENT_HOURS_PER_JOB=9
CURRENT_SECONDS_PER_INSTANCE=${LARGE_GPU_SLOW_RATE}
CURRENT_OUTPUT_PATH=/home/etg/"${CURRENT_INITIAL}"_"${CURRENT_JOB_COUNT}"_"${CURRENT_HOURS_PER_JOB}"_"${AGENT}"
CURRENT_REMAINDER_FN=remainder.tsv
CURRENT_REMAINDER_SRC_PATH="${CURRENT_OUTPUT_PATH}"/"${CURRENT_REMAINDER_FN}"
CURRENT_REMAINDER_DEST_PATH=/home/etg/r/Eli/CRICO_106k/"${AGENT}"/"${CURRENT_INITIAL}"_"${CURRENT_JOB_COUNT}"_"${CURRENT_HOURS_PER_JOB}"_"${CURRENT_REMAINDER_FN}"
python /home/etg/Repos/CRICO/data_engineering/partition_time_by_job_count_shards.py \
       --input_tsv /home/etg/Repos/CRICO/INCLUDED_PATHOLOGICAL_FIXED_405_6_72_remainder.tsv \
       --output_dir ${CURRENT_OUTPUT_PATH} \
       --initial ${CURRENT_INITIAL} \
       --job_count ${CURRENT_JOB_COUNT} \
       --hours_per_job ${CURRENT_HOURS_PER_JOB} \
       --seconds_per_instance ${CURRENT_SECONDS_PER_INSTANCE};
sudo rsync -ah --progress ${CURRENT_REMAINDER_SRC_PATH}  ${CURRENT_REMAINDER_DEST_PATH}
rm ${CURRENT_REMAINDER_SRC_PATH}
scp -r ${CURRENT_OUTPUT_PATH} ${E3_HOME}
